@startuml

class PatientController <<RestController>>
interface PatientController.Transformer
class PatientTransformer <<Service>>
interface Function<T,R>
class Patient103Root <<Generated>>
class Patient
class Query
class WebExceptionHandler <<RestControllerAdvice>>

PatientController *--> PatientController.Transformer
PatientTransformer --|> PatientController.Transformer
PatientController.Transformer --|> Function : <Patient103Root,Patient>
PatientController.Transformer ..> Patient103Root : <<process>>
PatientController.Transformer ..up..> Patient: <<create>>
PatientController ..> Patient: <<publish>>
PatientController ..> Query: <<create>>
WebExceptionHandler .. PatientController: <<decorates>>

@enduml
