@startuml

skinparam handwritten true
skinparam monochrome true
left to right direction

actor consumer
database "cdw"
database "id-store" as iddb
rectangle "dataquery"
rectangle "ids"

consumer -(0- dataquery
ids -- iddb

@enduml
